const KEY='academic-command-center-v2';
const seed=()=>structuredClone(SEMESTER_DATA);
let state=JSON.parse(localStorage.getItem(KEY))||seed();
const $=s=>document.querySelector(s);const daysUntil=d=>Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000);
function priority(a){const days=Math.max(0,daysUntil(a.due));return Math.round(a.weight*4+a.hours*3+a.difficulty*4+Math.max(0,30-days)*1.5+(a.type==='exam'?15:0)+(a.spec?8:0))}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function render(){const courses=$('#courseList'),select=$('#course');courses.innerHTML='';select.innerHTML='';state.courses.forEach(c=>{const pending=state.assignments.filter(a=>a.courseId===c.id&&!a.done);const impact=pending.reduce((s,a)=>s+a.weight,0);const grade=c.grade??null;const meta=c.gradeSystem==='specifications'?'Specifications grading · completion requirements':`${impact.toFixed(1)}% of weighted grade currently tracked`;courses.innerHTML+=`<div class="course"><div class="course-head"><span>${c.code?c.code+' · ':''}${c.name}</span><span>${grade===null?'—':grade+'%'}</span></div><small>${c.meeting||''}${c.location?' · '+c.location:''}</small><br><small>${pending.length} active items · ${meta}</small>${c.gradeSystem==='weighted'&&grade!==null?`<div class="bar"><i style="width:${Math.min(100,grade)}%"></i></div>`:''}</div>`;select.innerHTML+=`<option value="${c.id}">${c.code||''} ${c.name}</option>`});
const active=state.assignments.filter(a=>!a.done).sort((a,b)=>priority(b)-priority(a));const list=$('#assignmentList');list.innerHTML=active.length?'':'<p>No active assignments.</p>';active.forEach(a=>{const c=state.courses.find(x=>x.id===a.courseId),d=daysUntil(a.due);const impact=a.spec?'completion requirement':a.weight?`${a.weight}% grade impact`:'milestone';list.innerHTML+=`<div class="assignment"><div><strong>${a.title}${a.tentative?' (TBD/tentative)':''}</strong><br><small>${c?.code||c?.name} · ${d<0?'Overdue':d===0?'Due today':d+' days'} · ${impact} · ${a.hours}h</small></div><div><span class="score">Priority ${priority(a)}</span><button data-done="${a.id}" class="secondary">Done</button></div></div>`});
const total=active.length,due7=active.filter(a=>daysUntil(a.due)<=7).length,impact=active.reduce((s,a)=>s+a.weight,0),specs=active.filter(a=>a.spec).length;$('#stats').innerHTML=`<div class="stat"><span>Active work</span><strong>${total}</strong></div><div class="stat"><span>Due in 7 days</span><strong>${due7}</strong></div><div class="stat"><span>Weighted impact tracked</span><strong>${impact.toFixed(1)}%</strong></div><div class="stat"><span>Spec requirements</span><strong>${specs}</strong></div>`;
$('#strategist').innerHTML=active.length?strategy(active):'<p>Add assignments and the strategist will identify where your time matters most.</p>';$('#today').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'});document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{state.assignments.find(a=>a.id==b.dataset.done).done=true;save()})}
function strategy(a){const top=a[0],soon=a.filter(x=>daysUntil(x.due)<=7),hours=a.reduce((s,x)=>s+x.hours,0);return `<p><strong>Primary focus:</strong> ${top.title} is currently the highest-impact item based on grade impact, deadline, workload, difficulty, and exam/specification status.</p><p><strong>Next 7 days:</strong> ${soon.length} tracked item${soon.length===1?'':'s'} need attention. Estimated workload across all active items: <strong>${hours.toFixed(1)} hours</strong>.</p><p><strong>Important:</strong> weighted courses and specifications-graded courses are treated differently. Animal Behavior completion requirements are not artificially converted into fake grade percentages.</p>`}
$('#addCourseBtn').onclick=()=>$('#courseDialog').showModal();$('#courseForm').onsubmit=e=>{e.preventDefault();state.courses.push({id:'c'+Date.now(),name:$('#courseName').value.trim(),grade:+$('#currentGrade').value,gradeSystem:'weighted'});$('#courseDialog').close();e.target.reset();save()};$('#assignmentForm').onsubmit=e=>{e.preventDefault();state.assignments.push({id:'a'+Date.now(),courseId:$('#course').value,title:$('#title').value.trim(),due:$('#due').value,weight:+$('#weight').value||0,hours:+$('#hours').value,difficulty:+$('#difficulty').value,done:false,type:'assignment'});e.target.reset();save()};$('#resetDemo').onclick=()=>{state=seed();save()};render();